# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('answer_1', models.CharField(max_length=512)),
                ('answer_2', models.CharField(max_length=512)),
                ('creation', models.DateField()),
            ],
        ),
    ]
