# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_web_app', '0002_auto_20181106_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation',
            field=models.DateField(null=True),
        ),
    ]
