# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey_web_app', '0004_auto_20181106_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='creation',
        ),
        migrations.AddField(
            model_name='question',
            name='creation_dt',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name=b''),
        ),
        migrations.AlterField(
            model_name='question',
            name='age',
            field=models.IntegerField(null=True, verbose_name=b'\xe5\xb9\xb4\xe9\xbd\xa2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(max_length=512, null=True, verbose_name=b'\xe5\xa5\xbd\xe3\x81\x8d\xe3\x81\xaa\xe6\x98\xa0\xe7\x94\xbb\xe3\x81\xa8\xe3\x81\x9d\xe3\x81\xae\xe7\x90\x86\xe7\x94\xb1\xe3\x82\x92\xe6\x95\x99\xe3\x81\x88\xe3\x81\xa6\xe4\xb8\x8b\xe3\x81\x95\xe3\x81\x84'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(max_length=512, null=True, verbose_name=b'\xe5\xa5\xbd\xe3\x81\x8d\xe3\x81\xaa\xe3\x81\x8a\xe5\xba\x97\xe3\x81\xa8\xe3\x81\x9d\xe3\x81\xae\xe7\x90\x86\xe7\x94\xb1\xe3\x82\x92\xe6\x95\x99\xe3\x81\x88\xe3\x81\xa6\xe4\xb8\x8b\xe3\x81\x95\xe3\x81\x84'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=128, verbose_name=b'\xe6\xb0\x8f\xe5\x90\x8d'),
        ),
    ]
